<?php

return $sidebar = [
    'Categories' => [
        'interior decoration',
        'exterior decoration',
        'Kitchen',
        'Lighting',
        'Stationery',
        'Table arts',
    ],
    'Price' => [
        '0 - 50 €',
        '51 - 100 €',
        '101 - 200 €',
    ],
    'Color' => [
        'black',
        'white',
        'grey',
        'brown',
        'red',
        'orange',
        'yellow',
        'beige',
        'green',
        'blue',
        'purple',
        'pink',
    ],
    'Matter' => [
        'Wood',
        'Wool',
        'Clay',
        'Concrete',
        'Iron',
        'Porcelain',
        'Glass',
        'Cardboard',
        'Paper',
        'Tissue',
        'Cotton',
        'Acrylic',
        'PVC/Synthetic',
    ],
];